"""
Meta-Recipe Expansion Module

This module processes YAML CI pipeline recipes to allow for step inheritance and intelligent overrides,
reducing boilerplate when defining sequential training or processing steps.

Supported Meta-Tokens:
----------------------
1. <insert_from(rel_path)[slice]>
   - Reads a file and inserts the resulting lines as a list.
   - Slicing is optional and supports standard Python slice notation via commas or colons (e.g. [1,5] or [1:5]).
   - After slicing, empty or purely whitespace lines or lines starting with the character '#' are removed.
   - If placed inside a list (e.g., `- "<insert_from(args.txt)>"`), the lines expand directly into the parent list.
   - If used as a value (e.g., `args: "<insert_from(args.txt)>"`), the value becomes the generated list.

2. <repeat_last~N>
   - As a string: `- <repeat_last~N>`
     Creates an exact duplicate of a preceding step. `N=0` or omitted `~N` refers to the immediately
     preceding step. `N=1` refers to the step before that.
   - As a dictionary key: `- <repeat_last~N>: { overrides... }`
     Copies the target preceding step and applies the specified overrides via intelligent_merge.

   Merge Behavior:
   - Dictionaries: Deep-merged recursively.
   - CLI Argument Lists: Lists where every string starts with `--` are merged via
     prefix matching (e.g., `--lr=0.01` replaces `--lr=0.001`).
     NOTE: Because these merge by default, you MUST use <replace> to clear inherited flags.
   - Standard Lists: All other lists are completely overwritten by the override list
     by default. Use <extend> if you wish to preserve base elements.

3. <replace>
   - Used to force-overwrite keys, bypassing the recursive "intelligent" merge logic.
   - Mandated Use Case: Completely replacing a CLI argument list. Without <replace>,
     new flags are simply merged into the inherited list.
   - suffix is ignored for logic and only intended for uniqueness of keys.
   - Usage:
     <replace_suffix>:
       args: ["--new-starting-point"]  # This wipes all previous --flags
       nested_cfg: { key: value }      # Overwrites dict instead of merging

4. <extend>
   - Used to modify inherited lists. Supports slicing the base list and appending new items.
   - suffix is ignored for logic and only intended for uniqueness of keys.
   - Usage:
     <extend_suffix>:
       list_key: [item_to_append]
   - Slicing Usage: `<extend(start,end)_suffix>`
     Example: `<extend(1,3)(4,)_foo>: { binpacks: [new.binpack] }`
     Takes index 1 up to 3, and index 4 to the end of the base list, then appends 'new.binpack'.

5. <remove>
   - Assigning the string "<remove>" to a key deletes it from the resulting dictionary.
   - Usage: `key_to_delete: "<remove>"`

6. <insert_from_element(path)>
   - Extracts a specific node from within the same YAML file and inserts it.
   - Uses dot notation for dictionaries and bracket notation for lists.
   - Example: `<insert_from_element(training.steps[3].run)>`
   - Executes before `<repeat_last~N>`. It cannot retrieve steps generated by repeat directives.

Constraints & Edge Cases:
-------------------------
- The first step in a sequence cannot use `<repeat_last>`.
- `<repeat_last~N>` must not refer to an index before the first step.
- The script enforces that the first step has `run.resume: none`. Subsequent steps
  default to `previous_checkpoint` if not explicitly set.
- Directives like <extend> and <replace> must contain a dictionary of fields to operate on.
- Attempting to <extend> a non-list field in the base object will raise a ValueError.
"""

import copy
import re
import os

def resolve_inserts(node, dirpath):
    """
    Recursively scans the recipe for <insert_from(rel_path)[slice]> tokens.
    Expands them into lists of lines from the specified file.
    """
    insert_pattern = re.compile(r"^<insert_from\(([^)]+)\)(?:\[([^\]]+)\])?>$")

    if isinstance(node, dict):
        return {k: resolve_inserts(v, dirpath) for k, v in node.items()}

    elif isinstance(node, list):
        new_list = []
        for item in node:
            if isinstance(item, str):
                match = insert_pattern.match(item.strip())
                if match:
                    new_list.extend(_read_and_slice_file(match, dirpath))
                else:
                    new_list.append(resolve_inserts(item, dirpath))
            else:
                new_list.append(resolve_inserts(item, dirpath))
        return new_list

    elif isinstance(node, str):
        match = insert_pattern.match(node.strip())
        if match:
            return _read_and_slice_file(match, dirpath)
        return node

    else:
        return node

def _read_and_slice_file(match, dirpath):
    rel_path = match.group(1).strip()
    slice_str = match.group(2)

    active_dir = dirpath if dirpath is not None else os.getcwd()
    filepath = os.path.join(active_dir, rel_path)

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except Exception as e:
        raise ValueError(f"Failed to read {filepath} for <insert_from> directive: {e}")

    if slice_str:
        # Support both typical python colon syntax and comma separation
        parts = re.split(r'[,:]', slice_str)
        slice_args = [int(p.strip()) if p.strip() else None for p in parts]
        lines = lines[slice(*slice_args)]

    lines = [line.strip() for line in lines]
    # remove empty and comment lines
    lines = [line for line in lines if line and not line.startswith("#")]

    return lines

def _get_element_by_path(root, path_str):
    """
    Navigates a nested dictionary/list structure using dot and bracket notation.
    """
    keys = re.findall(r'[^.\[\]]+', path_str)
    current = root
    
    for key in keys:
        if isinstance(current, dict):
            if key not in current:
                raise KeyError(f"Key '{key}' not found traversing path '{path_str}'.")
            current = current[key]
        elif isinstance(current, list):
            try:
                idx = int(key)
                current = current[idx]
            except (ValueError, IndexError):
                raise IndexError(f"Invalid or out-of-bounds index '{key}' traversing path '{path_str}'.")
        else:
            raise ValueError(f"Cannot navigate into primitive value at '{key}' in path '{path_str}'.")
            
    return copy.deepcopy(current)

def resolve_element_inserts(node, root_doc):
    """
    Recursively finds <insert_from_element(...)> and replaces it with the target structure.
    Supports optional slicing for lists: <insert_from_element(path)[slice]>
    """
    # Updated regex to allow the optional [...] slice block at the end
    elem_pattern = re.compile(r"^<insert_from_element\(([^)]+)\)(?:\[([^\]]+)\])?>$")

    if isinstance(node, dict):
        return {k: resolve_element_inserts(v, root_doc) for k, v in node.items()}
    elif isinstance(node, list):
        return [resolve_element_inserts(item, root_doc) for item in node]
    elif isinstance(node, str):
        match = elem_pattern.match(node.strip())
        if match:
            path_str = match.group(1).strip()
            slice_str = match.group(2)
            
            # Extract the base element
            extracted = _get_element_by_path(root_doc, path_str)
            
            # Apply slicing if provided
            if slice_str:
                if not isinstance(extracted, list):
                    raise ValueError(f"Cannot apply slice '[{slice_str}]' to non-list element at '{path_str}'.")
                
                parts = re.split(r'[,:]', slice_str)
                slice_args = [int(p.strip()) if p.strip() else None for p in parts]
                extracted = extracted[slice(*slice_args)]

            # Recursively resolve in case the extracted target also contains self-references
            return resolve_element_inserts(extracted, root_doc)
        return node
    
    return node


def intelligent_merge(base, override):
    """
    Recursively deep-merges two dictionaries.
    """
    if isinstance(override, dict):
        merged = copy.deepcopy(base) if isinstance(base, dict) else {}

        for k, v in override.items():
            # 1. Handle Explicit Replacements
            if isinstance(k, str) and k.startswith("<replace"):
                if not isinstance(v, dict):
                    raise ValueError(f"{k} must contain a dictionary of fields to replace.")
                for rep_k, rep_v in v.items():
                    merged[rep_k] = copy.deepcopy(rep_v)

            # 2. Handle Extensions & Multiple Slicing of the BASE list
            elif isinstance(k, str) and k.startswith("<extend"):
                if not isinstance(v, dict):
                    raise ValueError(f"{k} must contain a dictionary of fields to extend.")

                # Extract the full block of parentheses, ignoring the suffix
                match = re.match(r"^<extend((?:\([^)]*\))*)(?:_.*?)?>$", k)
                if not match:
                    raise ValueError(f"Invalid syntax for extend directive: {k}")

                slices_str = match.group(1)
                # Find all individual slice arguments like '1,3' or ',-1'
                slice_args = re.findall(r'\(([^)]*)\)', slices_str) if slices_str else []

                for ext_k, ext_v in v.items():
                    if not isinstance(ext_v, list):
                        ext_v = [ext_v]

                    if ext_k not in merged or merged[ext_k] is None:
                        # If there is no base list, just take the new items
                        merged[ext_k] = copy.deepcopy(ext_v)
                    elif not isinstance(merged[ext_k], list):
                        raise ValueError(f"Cannot extend non-list field '{ext_k}'")
                    else:
                        base_list = merged[ext_k]
                        new_base = []

                        if not slice_args:
                            # No slices specified, keep the whole base list
                            new_base = copy.deepcopy(base_list)
                        else:
                            # Apply each slice to the base list and concatenate
                            for arg in slice_args:
                                parts = [p.strip() for p in arg.split(",")]
                                start, end = None, None
                                if len(parts) >= 1 and parts[0]:
                                    start = int(parts[0])
                                if len(parts) >= 2 and parts[1]:
                                    end = int(parts[1])

                                new_base.extend(copy.deepcopy(base_list[start:end]))

                        # Extend the cleanly sliced base with the new items
                        new_base.extend(copy.deepcopy(ext_v))
                        merged[ext_k] = new_base

            # 3. Handle Explicit Removals
            elif v == "<remove>":
                merged.pop(k, None)

            # 4. Standard Recursive Merge
            elif k in merged:
                merged[k] = intelligent_merge(merged[k], v)

            # 5. Populate New Keys
            else:
                merged[k] = intelligent_merge(None, v)

        return merged

    elif isinstance(override, list):
        if isinstance(base, list):
            # Heuristic: Intelligent CLI args replacement vs full array overwrite
            is_arg_list = len(override) > 0 and all(isinstance(x, str) and x.startswith("--") for x in override)
            if is_arg_list:
                merged = copy.deepcopy(base)
                for item in override:
                    if "=" in item:
                        prefix = item.split("=", 1)[0] + "="
                        replaced = False
                        for i, existing in enumerate(merged):
                            if isinstance(existing, str) and existing.startswith(prefix):
                                merged[i] = item
                                replaced = True
                                break
                        if not replaced:
                            merged.append(item)
                    else:
                        if item not in merged:
                            merged.append(item)
                return merged
        # Standard list without meta-directives overwrites the base entirely
        return copy.deepcopy(override)

    else:
        # Primitives or mismatched types (override replaces base entirely)
        return copy.deepcopy(override)


def enforce_resume_constraint(step, is_first_step, step_index):
    """
    Validates and enforces the 'resume' constraint, modifying the step in-place.
    """
    if "run" not in step:
        step["run"] = {}

    current_resume = step["run"].get("resume")

    if is_first_step:
        if current_resume != "none":
            print(f"WARNING (Step {step_index}): First step must have 'resume: none'. Overriding '{current_resume}' to 'none'.")
            step["run"]["resume"] = "none"
    else:
        valid_resumes = ["previous_model", "previous_checkpoint"]
        if current_resume not in valid_resumes:
            print(f"WARNING (Step {step_index}): 'resume: {current_resume}' is invalid for subsequent steps. Overriding to 'previous_checkpoint'.")
            step["run"]["resume"] = "previous_checkpoint"


def expand_meta_recipe(recipe, dirpath=None):
    """
    Resolves <insert_from> directives, expands '<repeat_last~N>', and applies overrides
    in the training steps sequentially. Modifies the recipe dictionary in-place.
    """

    recipe = resolve_element_inserts(recipe, recipe)
    recipe = resolve_inserts(recipe, dirpath)

    if "training" not in recipe or "steps" not in recipe["training"]:
        return recipe

    original_steps = recipe["training"]["steps"]
    if not original_steps:
        return recipe

    expanded_steps = []
    repeat_pattern = re.compile(r"^<repeat_last(?:~(\d+))?>$")

    for i, step in enumerate(original_steps):
        is_first = (i == 0)
        step_index = i + 1

        is_repeat = False
        repeat_n = 0
        overrides = {}

        # Detect <repeat_last~N> directive
        if isinstance(step, str):
            match = repeat_pattern.match(step)
            if match:
                is_repeat = True
                repeat_n = int(match.group(1)) if match.group(1) else 0
        elif isinstance(step, dict):
            for k, v in step.items():
                if isinstance(k, str):
                    match = repeat_pattern.match(k)
                    if match:
                        is_repeat = True
                        repeat_n = int(match.group(1)) if match.group(1) else 0
                        overrides = v if v is not None else {}
                        if not isinstance(overrides, dict):
                            raise ValueError(
                                f"Step {step_index} '{k}' overrides must be a mapping (dict), "
                                f"got {type(overrides).__name__!r}."
                            )
                        break

        # Handle formatting logic
        if is_first:
            if is_repeat:
                raise ValueError(f"Step {step_index} cannot use '<repeat_last>'. The base step must be fully defined.")

            new_step = copy.deepcopy(step)
            enforce_resume_constraint(new_step, is_first_step=True, step_index=step_index)
            expanded_steps.append(new_step)
            continue

        if is_repeat:
            target_idx = len(expanded_steps) - 1 - repeat_n
            if target_idx < 0:
                raise ValueError(f"Step {step_index} '<repeat_last~{repeat_n}>' references an index before the first step.")

            base_step = expanded_steps[target_idx]
            new_step = intelligent_merge(base_step, overrides)
            enforce_resume_constraint(new_step, is_first_step=False, step_index=step_index)
            expanded_steps.append(new_step)

        else:
            new_step = copy.deepcopy(step)
            enforce_resume_constraint(new_step, is_first_step=False, step_index=step_index)
            expanded_steps.append(new_step)

    recipe["training"]["steps"] = expanded_steps
    return recipe


if __name__ == "__main__":
    import argparse
    import sys
    import yaml

    class IndentSafeDumper(yaml.SafeDumper):
        def increase_indent(self, flow=False, indentless=False):
            return super(IndentSafeDumper, self).increase_indent(flow, False)

    DumperClass = IndentSafeDumper

    parser = argparse.ArgumentParser(
        description="Expand a meta-recipe YAML file containing <repeat_last> and <insert_from> directives.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "input_file",
        help="Path to the input meta-recipe YAML file."
    )
    parser.add_argument(
        "output_file",
        nargs="?",
        help="Optional path to the output YAML file. If omitted, prints to stdout."
    )

    args = parser.parse_args()

    # Base the dirpath evaluation on the location of the target YAML file.
    base_dirpath = os.path.dirname(os.path.abspath(args.input_file))

    try:
        with open(args.input_file, "r", encoding="utf-8") as f:
            recipe = yaml.safe_load(f)
    except FileNotFoundError:
        print(f"Error: Input file '{args.input_file}' not found.", file=sys.stderr)
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"Error parsing YAML: {e}", file=sys.stderr)
        sys.exit(1)

    # Expand the meta-recipe
    try:
        expanded_recipe = expand_meta_recipe(recipe, dirpath=base_dirpath)
    except ValueError as e:
        print(f"Expansion Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Output handling
    if args.output_file:
        with open(args.output_file, "w", encoding="utf-8") as f:
            yaml.dump(expanded_recipe, f, Dumper=DumperClass, default_flow_style=False, sort_keys=False, width=300)
        print(f"Expanded recipe successfully written to {args.output_file}")
    else:
        print(yaml.dump(expanded_recipe, Dumper=DumperClass, default_flow_style=False, sort_keys=False, width=300))