
training_binpacks: &training_binpacks
  - vondele/rescored/tb5dtm.binpack

model_config: &model_config
  features: Full_Threats+PP_3Wide+HalfKAv2_hm^
  l1: 1024
  l2: 32

optimize_flags: &optimize_flags
  <<: *model_config
  ft-optimize-count: 100000
  ft-optimize: true
  ft-compression: leb128

checkpoint2nnue_options: &checkpoint2nnue_options
  <<: *model_config
  ft-compression: leb128

common_run_options: &common_run_options
  epoch-size: 134217728
  batch-size: 131072
  one-cycle-steps: 4096000
  lr: "0.9e-3"
  start_lambda: 1.0
  end_lambda: 1.0
  pow_exp: 2.2458593774318936
  qp_asymmetry: 0.16123193074123665
  w1: 3.4992759013258348
  w2: 0.24990297747029686
  soft_early_fen_skipping: 55
  ply_x1: 15
  ply_x2: 25
  ply_x3: 35
  ply_x4: 45
  ply_y1: 0.4995834610368314
  ply_y2: 0.4755898062623219
  ply_y3: 0.7960350956742267
  ply_y4: 0.5268709998474687
  pc-y0: -0.021286239983835456
  pc-y1: 0.4630376436225087
  pc-y2: 0.8119190849177433
  pc-y3: 0.8432669372128858
  pc-y4: 0.8307417849554223
  cdb-path: "/workspace/cdb/chess-20260702/data"
  cdb-fraction: 0.99
  wld_filtered: False
  random_fen_skipping: 0
  early_fen_skipping: -1
  simple_eval_skipping: -1
  in_offset: 199.6164751319224
  out_offset: 208.55835423042265
  in_scaling: 288.6467157482683
  out_scaling: 289.58605293609645
  <<: *model_config

trainer: &trainer
  owner: vondele
  sha: 8b13e4eaad33a2852f0546f9060a982cbee110b2

reference_code: &reference_code
  owner: official-stockfish
  sha: 23cf5d827388e84d4389b40025ef401db4925f25
  target: profile-build

testing_code: &testing_code
  <<: *reference_code

# --- Grouped Structure Anchors for Redundancy Reduction ---
common_convert: &common_convert
  binpack: official-stockfish/master-binpacks/fishpack32.binpack
  checkpoint2nnue: *checkpoint2nnue_options
  optimize: *optimize_flags

common_step: &common_step
  convert: *common_convert
  trainer: *trainer

testing:
  crosscheck:
    trainer: *trainer
    binpack: official-stockfish/master-binpacks/fishpack32.binpack
    other_options:
      <<: *model_config
      count: 20000
  fastchess:
    code:
      owner: Disservin
      sha: b9008d08b9f375ef7810dc55da6ff223a3992cc2
    options:
      hash: 16
      max_rounds: 10000
      tc: 10+0.1
  reference:
    code: *reference_code
  steps: last
  testing:
    code: *testing_code


training:
  steps:
    # Pretraining
    - <<: *common_step
      run:
        resume: none
        binpacks: *training_binpacks
        max_epochs: 8400
        repetitions: 7
        other_options:
          <<: *common_run_options
