optimize_flags: &optimize_flags
  features: Full_Threats+HalfKAv2_hm^
  l1: 1024
  l2: 31
  ft-optimize-count: 100000
  ft-optimize: true
  ft-compression: leb128

checkpoint2nnue_options: &checkpoint2nnue_options
  features: Full_Threats+HalfKAv2_hm^
  l1: 1024
  l2: 31
  ft-compression: leb128

common_run_options: &common_run_options
  batch-size: 8192
  epoch-size: 100000
  features: Full_Threats+HalfKAv2_hm^
  l1: 1024
  l2: 31
  random-fen-skipping: 10
  soft-early-fen_skipping: 32
  w1: 3.3553547771220007
  w2: 0.7006821612968052
  pc-y0: -0.20
  pc-y1: 0.45
  pc-y2: 1.0
  pc-y3: 0.95
  pc-y4: 0.75

trainer: &trainer
  owner: sscg13
  sha: 8a026c6236f95d85fed3a69fdaf0f10896a4eda8

# --- Grouped Structure Anchors for Redundancy Reduction ---
common_convert: &common_convert
  binpack: official-stockfish/master-binpacks/fishpack32.binpack
  checkpoint2nnue: *checkpoint2nnue_options
  optimize: *optimize_flags

common_step: &common_step
  convert: *common_convert
  trainer: *trainer

official_code: &official_code
  owner: official-stockfish
  sha: 74a0a73715322608332038f7c0151ddf0609a59a
  target: profile-build

engine: &engine
  owner: sscg13
  sha: 9190b8240e4ead3f6ce0b194295c879208bbb96b
  target: profile-build
# ----------------------------------------------------------

testing:
  crosscheck:
    trainer: *trainer
    binpack: official-stockfish/master-binpacks/fishpack32.binpack
    other_options:
      features: Full_Threats+HalfKAv2_hm^
      l1: 1024
      l2: 31
      count: 5000
  fastchess:
    code:
      owner: Disservin
      sha: 541aef889206882de4823cf5a676d53ac5171c6f
    options:
      hash: 16
      max_rounds: 20
      tc: 3+0.03
    sprt:
      nElo_interval_midpoint: -0.75
      nElo_interval_width: 2
  reference:
    code: *official_code
  steps: all
  testing:
    code: *engine

training:
  steps:
    # Stage 1
    - <<: *common_step
      run:
        binpacks:
          - official-stockfish/master-binpacks/fishpack32.binpack
        max_epochs: 3
        repetitions: 2
        resume: none
        other_options:
          <<: *common_run_options
          lr: 4.375e-4
          gamma: 0.995
          start-lambda: 1.0
          end-lambda: 0.75
          early-fen-skipping: 10
          ply-x1: 0.0
          ply-y1: 0.01
          ply-x2: 14.0
          ply-y2: 0.20
          ply-x3: 18.5
          ply-y3: 0.50
          ply-x4: 29.5
          ply-y4: 0.80

    # Stage 2
    - <<: *common_step
      run:
        binpacks:
          - official-stockfish/master-binpacks/fishpack32.binpack
        max_epochs: 3
        repetitions: 1
        resume: previous_model
        other_options:
          <<: *common_run_options
          lr: 0.0010783148702050778
          gamma: 0.994446435229841
          pow-exp: 2.442037790427722
          qp-asymmetry: 0.15795949371005746
          start-lambda: 0.8460635942002347
          end-lambda: 0.7490913625693039
          in-scaling: 294.7193839807687
          out-scaling: 352.8750799744594
          in-offset: 281.4186220835457
          out-offset: 279.93991915496105
          early-fen-skipping: 18
          ply-x1: 0.00
          ply-y1: 0.025
          ply-x2: 22.0
          ply-y2: 0.05
          ply-x3: 25.5
          ply-y3: 0.20
          ply-x4: 29.5
          ply-y4: 0.80

    # Stage 3
    - <<: *common_step
      run:
        binpacks:
          - official-stockfish/master-binpacks/fishpack32.binpack
        max_epochs: 7
        repetitions: 2
        resume: previous_checkpoint
        other_options:
          <<: *common_run_options
          lr: 0.0010783148702050778
          gamma: 0.994446435229841
          pow-exp: 2.442037790427722
          qp-asymmetry: 0.15795949371005746
          start-lambda: 0.8460635942002347
          end-lambda: 0.7490913625693039
          in-scaling: 294.7193839807687
          out-scaling: 352.8750799744594
          in-offset: 281.4186220835457
          out-offset: 279.93991915496105
          early-fen-skipping: 18
          ply-x1: 0.00
          ply-y1: 0.025
          ply-x2: 22.0
          ply-y2: 0.05
          ply-x3: 25.5
          ply-y3: 0.20
          ply-x4: 29.5
          ply-y4: 0.80

