stage_one_binpacks: &stage_one_binpacks
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_0.binpack
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_1.binpack
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_2.binpack
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_3.binpack
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_4.binpack
  - official-stockfish/master-binpacks/nodes5000pv2_UHO.binpack
  - official-stockfish/master-binpacks/wrongIsRight_nodes5000pv2.binpack
  - official-stockfish/master-binpacks/multinet_pv-2_diff-100_nodes-5000.binpack
  - official-stockfish/master-binpacks/dfrc_n5000.binpack

stage_two_plus_binpacks: &stage_two_plus_binpacks
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_0.binpack
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_1.binpack
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_2.binpack
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_3.binpack
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_4.binpack
  - linrock/test60/test60-2021-11-nov-12tb7p.min-v2.binpack
  - linrock/test60/test60-2021-12-dec-12tb7p.min-v2.binpack
  - linrock/test77/test77-2021-12-dec-16tb7p.v6-dd.min.binpack
  - linrock/test78/test78-2022-01-to-05-jantomay-16tb7p.v6-dd.min.binpack
  - linrock/test79/test79-2022-04-apr-16tb7p.v6-dd.min.binpack
  - linrock/test79/test79-2022-05-may-16tb7p.v6-dd.min.binpack
  - linrock/test78/test78-2022-06-to-09-juntosep-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-06-jun-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-07-jul-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-08-aug-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-09-sep-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-10-oct-16tb7p.v6-dd.binpack
  - linrock/test80-2022/test80-2022-11-nov-16tb7p.v6-dd.min.binpack
  - linrock/test80-2023/test80-2023-01-jan-16tb7p.v6-sk20.min.binpack
  - linrock/test80-2023/test80-2023-02-feb-16tb7p.v6-dd.min.binpack
  - linrock/test80-2023/test80-2023-03-mar-2tb7p.v6-sk16.min.binpack
  - linrock/test80-2023/test80-2023-04-apr-2tb7p.v6-sk16.min.binpack
  - linrock/test80-2023/test80-2023-05-may-2tb7p.v6.min.binpack
  - linrock/test80-2023/test80-2023-06-jun-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-07-jul-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-08-aug-2tb7p.v6.min.binpack
  - linrock/test80-2023/test80-2023-09-sep-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-10-oct-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-11-nov-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-12-dec-2tb7p.min-v2.v6.binpack
  - linrock/test80-2024/test80-2024-01-jan-2tb7p.min-v2.v6.binpack
  - linrock/test80-2024/test80-2024-02-feb-2tb7p.min-v2.v6.binpack

model_config: &model_config
  features: Full_Threats+HalfKAv2_hm^
  l1: 1024
  l2: 32

optimize_flags: &optimize_flags
  <<: *model_config
  ft-optimize-count: 100000
  ft-optimize: true
  ft-compression: leb128

checkpoint2nnue_options: &checkpoint2nnue_options
  <<: *model_config
  ft-compression: leb128

common_run_options: &common_run_options
  optimizer-name: rangerlite
  validation-size: 250000000
  check-val-every-n-epoch: 50
  batch-size: 131072
  <<: *model_config
  factorized-weight-decay: 0.001
  random-fen-skipping: 10
  early-fen-skipping: 18
  soft-early-fen_skipping: 32
  pc-y0: -0.20
  pc-y1: 0.45
  pc-y2: 1.0
  pc-y3: 0.95
  pc-y4: 0.75

warmups_stage_options: &warmups_stage_options
  ply-x1: 0.0
  ply-y1: 0.01
  ply-x2: 14.0
  ply-y2: 0.20
  ply-x3: 18.5
  ply-y3: 0.50
  ply-x4: 29.5
  ply-y4: 0.80
  one-cycle-warmup-pct: 0.25
  one-cycle-final-div: "4e0"
  start-lambda: 1.0
  end-lambda: 0.74

advanced_stage_options: &advanced_stage_options
  ply-x1: 0.00
  ply-y1: 0.025
  ply-x2: 22.0
  ply-y2: 0.05
  ply-x3: 25.5
  ply-y3: 0.20
  ply-x4: 29.5
  ply-y4: 0.80
  pow-exp: 2.435
  qp-asymmetry: 0.23
  in-scaling: 300.0
  out-scaling: 350.0
  in-offset: 300.0
  out-offset: 300.0
  one-cycle-warmup-pct: 0.033
  one-cycle-final-div: "2e3"
  jitter-lambda-sample: 0.0034
  jitter-lambda-batch: 0.0062
  jitter-decay-lambda-batch: 0.999
  start-lambda: 0.74
  end-lambda: 0.74

trainer: &trainer
  owner: TonyCongqianWang
  sha: e8febfcfa19c95ccc29a2bc31ac9a1d6d910175a

reference_code: &reference_code
  owner: official-stockfish
  sha: 74a0a73715322608332038f7c0151ddf0609a59a
  target: build

testing_code: &testing_code
  owner: TonyCongqianWang
  sha: 68bed47d9aceba895b404453246e5261518135aa
  target: build

# --- Grouped Structure Anchors for Redundancy Reduction ---
common_convert: &common_convert
  binpack: official-stockfish/master-binpacks/fishpack32.binpack
  checkpoint2nnue: *checkpoint2nnue_options
  optimize: *optimize_flags

common_step: &common_step
  convert: *common_convert
  trainer: *trainer

common_run_stage_two_plus: &common_run_stage_two_plus
  binpacks: *stage_two_plus_binpacks
  repetitions: 1
  resume: previous_model

common_run_checkpoint: &common_run_checkpoint
  <<: *common_run_stage_two_plus
  resume: previous_checkpoint

# ----------------------------------------------------------

testing:
  crosscheck:
    trainer: *trainer
    binpack: official-stockfish/master-binpacks/fishpack32.binpack
    other_options:
      <<: *model_config
      count: 20000
  fastchess:
    code:
      owner: Disservin
      sha: b9008d08b9f375ef7810dc55da6ff223a3992cc2
    options:
      hash: 16
      max_rounds: 40000
      tc: 10+0.1
    sprt:
      nElo_interval_midpoint: 0
      nElo_interval_width: 2
  reference:
    code: *reference_code
  steps: all
  testing:
    code: *testing_code


training:
  steps:
    # Stage 1
    - <<: *common_step
      run:
        binpacks: *stage_one_binpacks
        max_epochs: 500
        other_options:
          <<: [*common_run_options, *warmups_stage_options]
          one-cycle-steps: 381500
          swa-start-epoch: 400
          lr: "0.5e-3"
        repetitions: 1
        resume: none

    # Stage 2
    - <<: *common_step
      run:
        <<: *common_run_stage_two_plus
        max_epochs: 5000
        repetitions: 3
        other_options:
          <<: [*common_run_options, *advanced_stage_options]
          one-cycle-steps: 3815000
          lr: "0.75e-3"


    # Stage 4 
    - <<: *common_step 
      run: 
        <<: *common_run_fine_tune 
        max_epochs: 50 
        other_options: 
          <<: [*common_run_options, *advanced_stage_options]
          batch_size: 65536
          one-cycle-steps: 76300 
          lr: "3e-5" 
          start-lambda: 1 
          end-lambda: 1 
          jitter-lambda-sample: 0.0 
          jitter-lambda-batch: 0.0 
          jitter-decay-lambda-batch: 0.0
      
