trainer: &trainer
  owner: official-stockfish
  sha: 89d572575441c927947fdc8b98c41719c530d120

sf_base: &sf_base
  owner: official-stockfish
  sha: b1053e60b7e0fe3187006c4d7f38dbd22eaff763
  target: profile-build

games: &games
  owner: Disservin
  sha: b9008d08b9f375ef7810dc55da6ff223a3992cc2

stage_one_binpacks: &stage_one_binpacks
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_0.binpack
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_1.binpack
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_2.binpack
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_3.binpack
  - vondele/from_kaggle_2/T60T70wIsRightFarseerT60T74T75T76.split_4.binpack
  - official-stockfish/master-binpacks/nodes5000pv2_UHO.binpack
  - official-stockfish/master-binpacks/wrongIsRight_nodes5000pv2.binpack
  - official-stockfish/master-binpacks/multinet_pv-2_diff-100_nodes-5000.binpack
  - official-stockfish/master-binpacks/dfrc_n5000.binpack

stage_two_plus_binpacks: &stage_two_plus_binpacks
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_0.binpack
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_1.binpack
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_2.binpack
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_3.binpack
  - vondele/from_kaggle_1/leela96-filt-v2.min.split_4.binpack
  - linrock/test60/test60-2021-11-nov-12tb7p.min-v2.binpack
  - linrock/test60/test60-2021-12-dec-12tb7p.min-v2.binpack
  - linrock/test77/test77-2021-12-dec-16tb7p.v6-dd.min.binpack
  - linrock/test78/test78-2022-01-to-05-jantomay-16tb7p.v6-dd.min.binpack
  - linrock/test79/test79-2022-04-apr-16tb7p.v6-dd.min.binpack
  - linrock/test79/test79-2022-05-may-16tb7p.v6-dd.min.binpack
  - linrock/test78/test78-2022-06-to-09-juntosep-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-06-jun-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-07-jul-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-08-aug-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-09-sep-16tb7p.v6-dd.min.binpack
  - linrock/test80-2022/test80-2022-10-oct-16tb7p.v6-dd.binpack
  - linrock/test80-2022/test80-2022-11-nov-16tb7p.v6-dd.min.binpack
  - linrock/test80-2023/test80-2023-01-jan-16tb7p.v6-sk20.min.binpack
  - linrock/test80-2023/test80-2023-02-feb-16tb7p.v6-dd.min.binpack
  - linrock/test80-2023/test80-2023-03-mar-2tb7p.v6-sk16.min.binpack
  - linrock/test80-2023/test80-2023-04-apr-2tb7p.v6-sk16.min.binpack
  - linrock/test80-2023/test80-2023-05-may-2tb7p.v6.min.binpack
  - linrock/test80-2023/test80-2023-06-jun-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-07-jul-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-08-aug-2tb7p.v6.min.binpack
  - linrock/test80-2023/test80-2023-09-sep-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-10-oct-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-11-nov-2tb7p.min-v2.v6.binpack
  - linrock/test80-2023/test80-2023-12-dec-2tb7p.min-v2.v6.binpack
  - linrock/test80-2024/test80-2024-01-jan-2tb7p.min-v2.v6.binpack
  - linrock/test80-2024/test80-2024-02-feb-2tb7p.min-v2.v6.binpack

optimize_flags: &optimize_flags
  features: Full_Threats+HalfKAv2_hm^
  l1: 1024
  l2: 31
  ft-optimize-count: 100000
  ft-optimize: true
  ft-compression: leb128

checkpoint2nnue_options: &checkpoint2nnue_options
  features: Full_Threats+HalfKAv2_hm^
  l1: 1024
  l2: 31
  ft-compression: leb128

common_run_options: &common_run_options
  optimizer-name: rangerlite
#  validation-size: 250000000
#  check-val-every-n-epoch: 25
  batch-size: 65536
  features: Full_Threats+HalfKAv2_hm^
  l1: 1024
  l2: 31
  factorized-weight-decay: 0.001
  random-fen-skipping: 10
  early-fen-skipping: 18
  soft-early-fen_skipping: 32
  pc-y0: -0.20
  pc-y1: 0.45
  pc-y2: 1.0
  pc-y3: 0.95
  pc-y4: 0.75

advanced_stage_options: &advanced_stage_options
  ply-x1: 0.00
  ply-y1: 0.025
  ply-x2: 22.0
  ply-y2: 0.05
  ply-x3: 25.5
  ply-y3: 0.20
  ply-x4: 29.5
  ply-y4: 0.80
  pow-exp: 2.442037790427722
  qp-asymmetry: 0.15795949371005746
  in-scaling: 294.7193839807687
  out-scaling: 352.8750799744594
  in-offset: 281.4186220835457
  out-offset: 279.93991915496105
  one-cycle-warmup-pct: 0.05
  one-cycle-final-div: "1e3"
  jitter-lambda-sample: 0.0030
  jitter-lambda-batch: 0.0100
  jitter-decay-lambda-batch: 0.999
  start-lambda: 0.76
  end-lambda: 0.76

# --- Grouped Structure Anchors for Redundancy Reduction ---
common_convert: &common_convert
  binpack: official-stockfish/master-binpacks/fishpack32.binpack
  checkpoint2nnue: *checkpoint2nnue_options
  optimize: *optimize_flags

common_step: &common_step
  convert: *common_convert
  trainer: *trainer

common_run_stage_two_plus: &common_run_stage_two_plus
  binpacks: *stage_two_plus_binpacks
  resume: previous_model

# ----------------------------------------------------------

testing:
  crosscheck:
    trainer: *trainer
    binpack: official-stockfish/master-binpacks/fishpack32.binpack
    other_options:
      features: Full_Threats+HalfKAv2_hm^
      l1: 1024
      l2: 31
      count: 20000
  fastchess:
    code: *games
    options:
      hash: 16
      max_rounds: 30000
      tc: 10+0.1
  reference:
    code: *sf_base
  steps: all
  testing:
    code: *sf_base

training:
  steps:
    # Stage 1
    - <<: *common_step
      run:
        binpacks: *stage_one_binpacks
        max_epochs: 250
        other_options:
          <<: *common_run_options
          one-cycle-steps: 381500
          lr: "2e-3"
          start-lambda: 1.0
          end-lambda: 0.75
          ply-x1: 0.0
          ply-y1: 0.01
          ply-x2: 14.0
          ply-y2: 0.20
          ply-x3: 18.5
          ply-y3: 0.50
          ply-x4: 29.5
          ply-y4: 0.80
        repetitions: 1
        resume: none

    # Stage 2
    - <<: *common_step
      run:
        <<: *common_run_stage_two_plus
        repetitions: 1
        max_epochs: 300
        other_options:
          <<: [*common_run_options, *advanced_stage_options]
          one-cycle-steps: 381500
          lr: "1.5e-3"
          swa-start-epoch: 250

    # Stage 3
    - <<: *common_step
      run:
        <<: *common_run_stage_two_plus
        repetitions: 1
        max_epochs: 550
        other_options:
          <<: [*common_run_options, *advanced_stage_options]
          one-cycle-steps: 763000
          lr: "1e-3"
          swa-start-epoch: 500

    # Stage 4
    - <<: *common_step
      run:
        <<: *common_run_stage_two_plus
        repetitions: 1
        max_epochs: 1050
        other_options:
          <<: [*common_run_options, *advanced_stage_options]
          one-cycle-steps: 1526000
          lr: "0.67e-3"
          swa-start-epoch: 1000

    # Stage 5
    - <<: *common_step
      run:
        <<: *common_run_stage_two_plus
        repetitions: 2
        max_epochs: 1850
        other_options:
          <<: [*common_run_options, *advanced_stage_options]
          one-cycle-steps: 3052000
          lr: "0.5e-3"
          swa-start-epoch: 1800
